#!/bin/bash
for j in 200 300 500 800 1000 1500 2000
do
    for i in latt rand
    do
    #sbatch -a 1-128 runner.sh CKuramoto.py $j ${i}_8
    sbatch -p epyc runner.sh plotter.py $j ${i}_8
    done
done


